// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct Recipe: Codable, Identifiable {
    /// The unique recipe identifier.
    ///
    /// Example: 2380570
    public var id: Int
    /// The title of the recipe.
    ///
    /// Example: "BBQ Sticky Ribs"
    public var title: String
    /// The story behind the recipe.
    ///
    /// Example: "Pork ribs marinated overnight in a sweet barbecue sauce slowly cooked and finished off on a BBQ"
    public var story: String
    /// A URL to the main image of the recipe, or null if one was not specified.
    ///
    /// Example: "https://img-global.cpcdn.com/recipes/65555efe64df98ce/m/photo.jpg"
    public var imageURL: URL?
    /// The date that the recipe was published in ISO8601 format.
    ///
    /// Example: "2017-07-05T02:34:00+00:00"
    public var publishedAt: Date
    public var user: User
    /// An array of ingredients used within the recipe.
    ///
    /// Example: ["2 kg pork ribs", "400 g chopped tomatoes", "5 garlic cloves", "100 g soft brown sugar", "75 ml maple syrup", "150 ml ketchup", "150 ml BBQ sauce", "150 ml Honey Jack Daniels whiskey", "50 ml cider vinegar", "2 tbsp black treacle", "3 tbsp soy sauce", "2 tbsp Worcestershire sauce"]
    public var ingredients: [String]
    /// An array of steps to follow within the recipe.
    public var steps: [Step]

    public init(id: Int, title: String, story: String, imageURL: URL? = nil, publishedAt: Date, user: User, ingredients: [String], steps: [Step]) {
        self.id = id
        self.title = title
        self.story = story
        self.imageURL = imageURL
        self.publishedAt = publishedAt
        self.user = user
        self.ingredients = ingredients
        self.steps = steps
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Int.self, forKey: "id")
        self.title = try values.decode(String.self, forKey: "title")
        self.story = try values.decode(String.self, forKey: "story")
        self.imageURL = try values.decodeIfPresent(URL.self, forKey: "image_url")
        self.publishedAt = try values.decode(Date.self, forKey: "published_at")
        self.user = try values.decode(User.self, forKey: "user")
        self.ingredients = try values.decode([String].self, forKey: "ingredients")
        self.steps = try values.decode([Step].self, forKey: "steps")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(title, forKey: "title")
        try values.encode(story, forKey: "story")
        try values.encodeIfPresent(imageURL, forKey: "image_url")
        try values.encode(publishedAt, forKey: "published_at")
        try values.encode(user, forKey: "user")
        try values.encode(ingredients, forKey: "ingredients")
        try values.encode(steps, forKey: "steps")
    }
}
