// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct Step: Codable {
    /// The instructions for the step.
    ///
    /// Example: "Crush the garlic cloves and add all ingredients apart from the ribs into a pan"
    public var description: String
    /// An array of up to three image URLs associated with the step.
    ///
    /// Example: ["https://img-global.cpcdn.com/steps/0606534c251df2e5/m/photo.jpg"]
    public var imageURLs: [URL]

    public init(description: String, imageURLs: [URL]) {
        self.description = description
        self.imageURLs = imageURLs
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.description = try values.decode(String.self, forKey: "description")
        self.imageURLs = try values.decode([URL].self, forKey: "image_urls")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(description, forKey: "description")
        try values.encode(imageURLs, forKey: "image_urls")
    }
}
