// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct User: Codable {
    /// The name of the user.
    ///
    /// Example: "Liam Nichols"
    public var name: String
    /// A URL to the user profile image, or null if one was not specified.
    ///
    /// Example: "https://img-global.cpcdn.com/users/f34ef79fabdb58a4/m/photo.jpg"
    public var imageURL: URL?

    public init(name: String, imageURL: URL? = nil) {
        self.name = name
        self.imageURL = imageURL
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.name = try values.decode(String.self, forKey: "name")
        self.imageURL = try values.decodeIfPresent(URL.self, forKey: "image_url")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(name, forKey: "name")
        try values.encodeIfPresent(imageURL, forKey: "image_url")
    }
}
