// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths {
    /// All Recipes
    ///
    /// Returns an array of all Recipe models in order of most recently published.
    static public var getAllRecipes: Request<[DemoAPI.Recipe]> {
        Request(method: "GET", url: "/api/recipes", id: "getAllRecipes")
    }
}
