// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths {
    /// Find Recipes in a Collection
    ///
    /// Returns an ordered array of Recipe models in the given Collection.
    static public func getCollectionRecipes(id: Int) -> Request<[DemoAPI.Recipe]> {
        Request(method: "GET", url: "/api/collections/\(id)/recipes", id: "getCollectionRecipes")
    }
}
