// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths {
    /// Find a Collection by ID
    ///
    /// Returns a single Collection model associated with the given identifier.
    static public func getCollection(id: Int) -> Request<DemoAPI.Collection> {
        Request(method: "GET", url: "/api/collections/\(id)", id: "getCollection")
    }
}
